openwallet-foundation/askar

Cargo.toml
askar-crypto/Cargo.toml
askar-crypto/benches/enc.rs
askar-crypto/src/alg/aes/cbc_hmac.rs
askar-crypto/src/alg/aes/mod.rs
askar-crypto/src/alg/any.rs
askar-crypto/src/alg/bls.rs
askar-crypto/src/alg/chacha20.rs
askar-crypto/src/alg/ed25519.rs
askar-crypto/src/alg/k256.rs
askar-crypto/src/alg/p256.rs
askar-crypto/src/alg/x25519.rs
askar-crypto/src/buffer/array.rs
askar-crypto/src/buffer/secret.rs
askar-crypto/src/encrypt/crypto_box.rs
askar-crypto/src/encrypt/mod.rs
askar-crypto/src/lib.rs
askar-crypto/src/random.rs
askar-crypto/src/repr.rs
src/kms/local_key.rs
src/protect/hmac_key.rs
src/protect/profile_key.rs
src/protect/store_key.rs
wrappers/python/aries_askar/__init__.py
wrappers/python/aries_askar/bindings.py
wrappers/python/aries_askar/key.py
wrappers/python/aries_askar/types.py
wrappers/python/aries_askar/version.py
wrappers/python/tests/test_keys.py

Add KeyMaterial trait, updates to KeyGen trait

0.2.0 updates

---

README.md
askar-bbs/Cargo.toml
askar-bbs/README.md
askar-bbs/benches/blind_sign.rs
askar-bbs/benches/proof.rs
askar-bbs/benches/signature.rs
askar-bbs/src/challenge.rs
askar-bbs/src/commitment.rs
askar-bbs/src/generators.rs
askar-bbs/src/hash.rs
askar-bbs/src/lib.rs
askar-bbs/src/proof.rs
askar-bbs/src/signature.rs
askar-bbs/src/util.rs
askar-bbs/tests/blind_sign.rs
askar-bbs/tests/proof.rs
askar-bbs/tests/signature.rs
askar-crypto/README.md

- Misc API adjustments
- Add accessors for proof response values and test of cross-signature message equality proof
- Add some (likely temporary) discriminator values for proofs

BBS+ updates

---

src/ffi/store.rs

Use lock_arc instead of try_lock_arc when borrowing store

---

.github/workflows/build-ios.yml

Fixes the iOS build pipeline
related to: https://github.com/hyperledger/aries-askar/issues/67

use toolchain and not cross

---

Cargo.toml
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/package.json
wrappers/python/aries_askar/version.py

Signed-off-by: Timo Glastra <timo@animo.id>

chore: update version to 0.2.8-dev.1

---

.github/workflows/build.yml
.gitignore
build-xcframework.sh
wrappers/javascript/aries-askar-react-native/android/CMakeLists.txt
wrappers/javascript/aries-askar-react-native/android/build.gradle
wrappers/javascript/aries-askar-react-native/aries-askar.podspec

feat(js): setup React Native

---

wrappers/javascript/aries-askar-react-native/android/cpp-adapter.cpp
wrappers/javascript/aries-askar-react-native/cpp/HostObject.cpp
wrappers/javascript/aries-askar-react-native/cpp/HostObject.h
wrappers/javascript/aries-askar-react-native/cpp/ariesAskar.cpp
wrappers/javascript/aries-askar-react-native/cpp/turboModuleUtility.cpp
wrappers/javascript/aries-askar-react-native/cpp/turboModuleUtility.h
wrappers/javascript/aries-askar-react-native/ios/AriesAskar.mm

fix(js): allow multiple turbo modules to be registered

---

Cargo.toml
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json

chore: update version

---

wrappers/javascript/aries-askar-react-native/cpp/turboModuleUtility.cpp

fix(js): downcast with static cast

---

wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json

- When this is merged I will do a "publish wrappers" GH action.

chore(js): update version

---

wrappers/javascript/aries-askar-react-native/android/CMakeLists.txt
wrappers/javascript/aries-askar-react-native/android/build.gradle

Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>

fix(rn): android works with JSC and Hermes

---

Cargo.toml
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/aries_askar/version.py

Signed-off-by: Berend Sliedrecht <blu3beri@proton.me>

chore: update to stable version

---

.github/workflows/build.yml
wrappers/javascript/aries-askar-nodejs/README.md
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-nodejs/src/ffi/alloc.ts
wrappers/javascript/aries-askar-nodejs/src/ffi/callback.ts
wrappers/javascript/aries-askar-nodejs/src/ffi/conversion.ts
wrappers/javascript/aries-askar-nodejs/src/ffi/primitives.ts
wrappers/javascript/aries-askar-nodejs/src/ffi/serialize.ts
wrappers/javascript/aries-askar-nodejs/src/ffi/structures.ts
wrappers/javascript/aries-askar-nodejs/src/library/bindings.ts
wrappers/javascript/aries-askar-nodejs/src/library/register.ts
wrappers/javascript/package.json
wrappers/javascript/yarn.lock

Similar approach as https://github.com/hyperledger/anoncreds-rs/pull/231 to make an easier set up in Node.js environment.

fix(js)!: use patched ref-napi/ffi-napi for nodejs

---

askar-storage/src/backend/sqlite/provision.rs

Retry database file removal on windows

---

.github/workflows/build.yml

An attempt to resolve the everlasting 'pending' required status checks

Combine checks for matrix build steps

---

Cargo.toml
wrappers/javascript/aries-askar-nodejs/README.md
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/README.md
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/README.md
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/aries_askar/version.py

Need to wait with releasing until #177 is merged
@andrewwhitehead  @berendsliedrecht @genaris all good to make a first 0.3.0 dev release?

chore: update version to 0.3.0 dev

---

Cargo.lock
Cargo.toml
askar-storage/Cargo.toml
src/lib.rs

Also cleans up some automatic feature flags based on optional dependencies.
Fixes #215

Update sqlx to 0.7.3

---

Cargo.lock
Cargo.toml
askar-crypto/Cargo.toml
wrappers/javascript/aries-askar-nodejs/README.md
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/README.md
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/README.md
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/aries_askar/version.py

chore: update version to 0.3.1 (js 0.2.0-dev.6)

---

Cargo.lock
wrappers/javascript/aries-askar-nodejs/package.json
wrappers/javascript/aries-askar-react-native/package.json
wrappers/javascript/aries-askar-shared/package.json
wrappers/javascript/lerna.json

Updates JS wrapper to 0.2.0 stable.

chore(js): update to stable 0.2.0

---

wrappers/javascript/aries-askar-nodejs/src/ffi/serialize.ts
wrappers/javascript/aries-askar-nodejs/tests/keys.test.ts

Should address at least part of #237

fix: correctly serliaize for buffer

---

.github/workflows/build.yml

Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>

build: allow action to create release

---

wrappers/javascript/.prettierignore
wrappers/javascript/lerna.json
wrappers/javascript/package.json
wrappers/javascript/pnpm-lock.yaml

Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>

fix(js): lerna setup

---

wrappers/javascript/pnpm-workspace.yaml

Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>

chore(js): set pnpm workspace correct

---

askar-crypto/src/alg/aes/mod.rs
askar-crypto/src/alg/any.rs
askar-crypto/src/alg/chacha20.rs
askar-crypto/src/alg/ed25519.rs
askar-crypto/src/alg/k256.rs
askar-crypto/src/alg/p256.rs
askar-crypto/src/alg/p384.rs
askar-crypto/src/alg/x25519.rs
wrappers/python/tests/test_keys.py
wrappers/python/tests/test_store.py

Implement JWK import for symmetric keys

---

.github/workflows/scorecard.yml

Signed-off-by: Stephen Curran <swcurran@gmail.com>

Add OpenSSF Scorecard to the repository

---

Cargo.toml
askar-crypto/Cargo.toml
askar-storage/Cargo.toml

Signed-off-by: Berend Sliedrecht <berend@animo.id>

chore: increment version for new Android release

---

askar-storage/src/any.rs
askar-storage/src/backend/db_utils.rs
askar-storage/src/backend/mod.rs
askar-storage/src/backend/postgres/mod.rs
askar-storage/src/backend/postgres/provision.rs
askar-storage/src/backend/sqlite/mod.rs
askar-storage/src/protect/mod.rs
src/ffi/store.rs
src/store.rs
wrappers/python/aries_askar/bindings/__init__.py
wrappers/python/aries_askar/store.py
wrappers/python/tests/test_store.py

Add copying and renaming of individual Store profiles
