openwallet-foundation/askar

Cargo.toml, src/ffi/log.rs, src/postgres/provision.rs, src/sqlite/provision.rs, wrappers/python/aries_askar/bindings.py, wrappers/python/aries_askar/version.py, wrappers/python/demo/perf.py, wrappers/python/demo/test.py
Adds more options for log filtering, respecting RUST_LOG when defined, and defaulting to the same level as the Python logger in that wrapper. Moving sqlx query logging to the DEBUG level should improve performance in general.
=> Logging performance improvements

src/ffi/key.rs, wrappers/python/aries_askar/ecdh.py, wrappers/python/tests/test_jose_ecdh.py
FFI: Avoid a trapped panic when a null pointer is passed as a key algorithm name
Python wrapper: Add a `cc_tag` parameter to `Ecdh1PU.receiver_unwrap_key`, extend unit test
=> ECDH-1PU minor fixes

.github/workflows/build.yml, Cargo.toml, askar-crypto/Cargo.toml, src/backend/db_utils.rs, src/backend/postgres/mod.rs, src/backend/postgres/test_db.rs, src/backend/sqlite/mod.rs, tests/docker_pg.sh, wrappers/python/aries_askar/store.py, wrappers/python/aries_askar/version.py, wrappers/python/tests/test_store.py
This would be a security issue, except that it was not possible to actually use the newly created profiles.
Fixes #19
=> Fix: encrypt keys for new profiles

askar-crypto/src/alg/p256.rs
* Fixes #26 Incorrect signature type is used for P256KeyPair
* Use compatible signature type inside of KeySign::write_signature for P256KeyPair
=> Fixes #26 Incorrect signature type is used for P256KeyPair

Cargo.toml, askar-crypto/Cargo.toml, askar-crypto/src/alg/any.rs, askar-crypto/src/alg/bls.rs, src/ffi/error.rs, wrappers/python/aries_askar/bindings.py, wrappers/python/aries_askar/version.py
Consistent with previous specifications, although OKP is preferred (EC keys tend to have both `x` and `y` components).
Updates env_logger to 0.9.
Updates library version to 0.2.4.
=> Accept EC key type for BLS keys

src/lib.rs, src/protect/kdf/argon2.rs, src/protect/kdf/mod.rs
Askar exposes `StoreKeyMethod` enum (it is used for wallet creation and opening) but for using `DeriveKey` variant we need to pass `KdfMethod` object which is crate private.
=> Exposed Argon enum in Rust to use it for key derivation

wrappers/javascript/aries-askar-nodejs/src/NodeJSAriesAskar.ts, wrappers/javascript/aries-askar-react-native/src/ReactNativeAriesAskar.ts
For some reason, JS wrappers were defaulting offset to -1. This throws an `OFFSET must not be negative` error when using a PostgreSQL backend.
=> fix(js): set scan offset to 0 if not defined

wrappers/javascript/aries-askar-nodejs/tests/keys.test.ts, wrappers/javascript/aries-askar-shared/src/enums/KeyAlgs.ts
G1G2 variant of BLS12381 is supported by Askar but is not available in JavaScript wrappers. In this PR we add the constant to `KeyAlgs` enum.
=> feat(js): add Bls12381G1G2 to supported key algos

Cargo.toml, src/ffi/handle.rs, src/ffi/log.rs, src/ffi/mod.rs, src/future.rs, wrappers/python/aries_askar/bindings/__init__.py, wrappers/python/aries_askar/bindings/lib.py, wrappers/python/aries_askar/store.py
In my tests this appears to fix the intermittent failures when terminating after running the Python wrapper tests.
=> Add FFI method to terminate worker threads; fix custom logger disabling

.github/workflows/build.yml, askar-bbs/Cargo.toml, askar-crypto/Cargo.toml
`csv` 1.2 was released, and requires Rust 1.60. This avoids requiring the newer Rust version for the current stable release.
=> CI build fixes

wrappers/javascript/aries-askar-nodejs/src/NodeJSAriesAskar.ts, wrappers/javascript/aries-askar-nodejs/tests/cryptoBox.test.ts, wrappers/javascript/aries-askar-nodejs/tests/joseEcdh.test.ts, wrappers/javascript/aries-askar-nodejs/tests/store.test.ts, wrappers/javascript/aries-askar-shared/src/ariesAskar/AriesAskar.ts, wrappers/javascript/aries-askar-shared/src/crypto/Ecdh1PU.ts, wrappers/javascript/aries-askar-shared/src/crypto/EcdhEs.ts, wrappers/javascript/aries-askar-shared/src/crypto/handles.ts, wrappers/javascript/aries-askar-shared/src/store/Session.ts
As there is not a destructor in JS, objects must be freed manually. This PR attempts to free any native object after it is used, making life easier to consumer applications. 
If this approach is correct, the only objects an app using this library should care about is `Key` (for which I added the missing call to `keyFree`).
@blu3beri let me know if concepts applied here are correct so I can replicate for anoncreds-rs.
=> fix(js): free key and entry objects

wrappers/javascript/aries-askar-shared/src/store/Scan.ts
When using `Scan.fetchAll` I found that the scan handle was not always properly freed. It turns out that this had to do with an error thrown when calling `scanNext` due to no records have been found (related issue https://github.com/hyperledger/aries-askar/issues/77), which prevented the code from executing the scanFree call.
So here we simply add a try-finally to make sure it is always being called.
=> fix(js): ensure scan is freed after fetchAll

wrappers/javascript/aries-askar-nodejs/src/NodeJSAriesAskar.ts, wrappers/javascript/aries-askar-nodejs/tests/store.test.ts, wrappers/javascript/aries-askar-react-native/cpp/HostObject.cpp, wrappers/javascript/aries-askar-react-native/cpp/ariesAskar.cpp, wrappers/javascript/aries-askar-react-native/cpp/ariesAskar.h, wrappers/javascript/aries-askar-react-native/cpp/turboModuleUtility.cpp, wrappers/javascript/aries-askar-react-native/cpp/turboModuleUtility.h, wrappers/javascript/aries-askar-react-native/native/aries_askar.node, wrappers/javascript/aries-askar-react-native/src/ReactNativeAriesAskar.ts, wrappers/javascript/aries-askar-react-native/src/library/NativeBindings.ts, wrappers/javascript/aries-askar-react-native/src/utils/handleError.ts, wrappers/javascript/aries-askar-react-native/src/utils/index.ts, wrappers/javascript/aries-askar-react-native/src/utils/serialize.ts, wrappers/javascript/aries-askar-shared/src/ariesAskar/AriesAskar.ts, wrappers/javascript/aries-askar-shared/src/crypto/handles.ts, wrappers/javascript/aries-askar-shared/src/error.ts, wrappers/javascript/aries-askar-shared/src/store/Entry.ts, wrappers/javascript/aries-askar-shared/src/store/EntryList.ts, wrappers/javascript/aries-askar-shared/src/store/KeyEntry.ts, wrappers/javascript/aries-askar-shared/src/store/Scan.ts, wrappers/javascript/aries-askar-shared/src/store/Session.ts
This PR contains several fixes from integrating aries askar into react native. 
Mainly it resolves:
- https://github.com/hyperledger/aries-askar/issues/77
- incorrect creation of errors in React Native (no AriesAskarError, but string)
- null pointer handling
Draft as it still needs to be tested fully in React Native
=> fix(js): several fixes for js wrapper

src/backend/sqlite/provision.rs
Now using a default maximum number of connections between 2 and 8 even when the detected number of CPUs is higher or lower.
Related: #109
=> Restrict default max conns to a range for sqlite

wrappers/javascript/aries-askar-nodejs/src/NodeJSAriesAskar.ts, wrappers/javascript/aries-askar-shared/src/ariesAskar/AriesAskar.ts, wrappers/javascript/aries-askar-shared/src/crypto/handles.ts
There was a small inconsistency between the key handle name for `keyFree` between node.js and react native. As all other methods use `localKeyHandle` (which the RN also expected), i've changed the method and node implementation.
=> fix(js): key handle name

wrappers/javascript/aries-askar-shared/src/store/Scan.ts
There is an unnecessary chunk variable (inherited from previous Indy SDK implementation in AFJ) that is preventing `fetchAll` to retrieve all records when they are more than PAGE_SIZE. As a result, a given Scan cannot return more than 32 entries.
Simply checking for `listHandle` (`scanNext` return value) validity seems to be enough to determine if there are no more matching records.
=> fix(js): scan fetch record limit

.github/workflows/build.yml, build-xcframework.sh
- Use static libraries for iOS for lower version compatibility
- Use rust 1.61.0 in CI as hashbrown needs 1.61.0 minimum.
=> chore: lower iOS compatibility

Cargo.toml, wrappers/javascript/aries-askar-nodejs/package.json, wrappers/javascript/aries-askar-react-native/package.json, wrappers/javascript/aries-askar-shared/package.json, wrappers/javascript/lerna.json, wrappers/python/aries_askar/version.py
Discussed with @andrewwhitehead and we will do a quick 0.2.9-dev.1 release to make sure all the iOS fixes are correct and release 2.9.0 when everything is working.
=> chore: update version

wrappers/python/aries_askar/store.py, wrappers/python/tests/test_store.py
I don't think we can change the default commit behaviour for transactions as in #52 (at least not yet), but this allows them to auto-commit as long as an exception isn't raised.
=> (python) Add autocommit flag to transaction

.github/workflows/build.yml, wrappers/javascript/aries-askar-nodejs/README.md, wrappers/javascript/aries-askar-nodejs/package.json, wrappers/javascript/aries-askar-react-native/README.md, wrappers/javascript/aries-askar-react-native/package.json, wrappers/javascript/aries-askar-shared/README.md, wrappers/javascript/aries-askar-shared/package.json, wrappers/javascript/lerna.json
Updates version for the JS wrapper to 0.1.1 so we can make another release before updating the JS wrapper with the changes for the 0.3 release.
Also adds new options publish-javascript-wrapper and publish-python-wrapper instead of publish-wrappers in the CI, so we can release the JS wrapper separately.
Also adds a version compatibility between Aries Askar version and the JS wrapper version.
=> chore: update version for js wrapper

askar-storage/src/any.rs, askar-storage/src/backend/db_utils.rs, askar-storage/src/backend/mod.rs, askar-storage/src/backend/postgres/mod.rs, askar-storage/src/backend/postgres/provision.rs, askar-storage/src/backend/postgres/test_db.rs, askar-storage/src/backend/sqlite/mod.rs, askar-storage/src/backend/sqlite/provision.rs, askar-storage/src/entry.rs, askar-storage/src/protect/pass_key.rs, askar-storage/src/protect/profile_key.rs, askar-storage/tests/backends.rs, askar-storage/tests/utils/mod.rs, src/ffi/result_list.rs, src/ffi/store.rs, src/kms/mod.rs, src/store.rs, wrappers/python/aries_askar/bindings/__init__.py, wrappers/python/aries_askar/bindings/handle.py, wrappers/python/aries_askar/bindings/lib.py, wrappers/python/aries_askar/store.py, wrappers/python/tests/test_store.py
Fixes #18
Also adds methods to get and set the default profile (opened when none is specified).
=> Support copying individual profiles or a whole Store

wrappers/javascript/aries-askar-shared/src/enums/KeyAlgs.ts
This simply adds a constant for P384 key algo support (added in #157) from JS.
=> fix(js): add p384 key algo

askar-storage/src/any.rs, askar-storage/src/backend/db_utils.rs, askar-storage/src/backend/mod.rs, askar-storage/src/backend/postgres/mod.rs, askar-storage/src/backend/sqlite/mod.rs, askar-storage/tests/backends.rs, askar-storage/tests/utils/mod.rs, src/store.rs, wrappers/javascript/aries-askar-nodejs/tests/store.test.ts, wrappers/python/tests/test_store.py
Fixes #163 
For Postgres, this also ensures that a profile cannot be removed while there is an active transaction against it.
Includes a fix for the persistent test failure copying a Store instance on Windows.
=> Add method to ping store sessions; verify profile existence when opening a session

askar-storage/src/any.rs, askar-storage/src/backend/postgres/provision.rs, askar-storage/src/backend/postgres/test_db.rs, askar-storage/src/backend/sqlite/provision.rs, askar-storage/src/options.rs
For support of Postgres 15 where the CREATE permission isn't automatically granted on the 'public' schema.
Adds a new optional 'schema' parameter for postgres connection URLs (ie. `postgres://user:pw@host/db?schema=public`). When not set, the schema now defaults to the username when creating new tables.
For new stores,
- If the database is newly created, then the database owner is set explicitly
- A new schema is created in the database, with the same name as the user. This is consistent with the default search path: `('$user', public)`
- All tables are created in the specified schema
For existing stores,
- If the schema isn't specified, then all schemas in the search path are checked for the config table (not just 'public')
- When the schema is set explicitly in the connection URL, the …
=> Postgres provisioning fixes

askar-storage/src/backend/db_utils.rs, askar-storage/src/backend/postgres/mod.rs, askar-storage/src/backend/postgres/provision.rs, askar-storage/src/backend/sqlite/mod.rs, askar-storage/src/backend/sqlite/provision.rs, askar-storage/tests/backends.rs
Rather than relying on a closing task to be scheduled on the async runtime, we can actively return pool connections in most cases. It seems like this may help avoid the intermittent failure of the `copy_db` test on Windows due to a file lock.
=> Actively return pool connections

askar-storage/src/backend/sqlite/provision.rs
Based on testing against ACA-Py. I believe that the `available_parallelism` method comes up with a lower number than `num_cpus::count` did on Github CI, but in general a maximum of 2 connections does seem too low.
=> Adjust lower maximum number of connections for sqlite

wrappers/javascript/aries-askar-nodejs/package.json, wrappers/javascript/aries-askar-react-native/package.json, wrappers/javascript/aries-askar-shared/package.json, wrappers/javascript/lerna.json
Updates the version of the JS wrappers for Askar to a new dev version.
I was a bit confused by the versions as the Python and Cargo versions were already set to 0.3, but no release was made yet. 
@andrewwhitehead are we good to make a release in the main branch for the Python and Rust binaries? Then we can merge this PR and release it, as this depends on the 0.3 library being released now
=> chore(js): update version to dev.3

Cargo.toml, benches/README.md, benches/benchmark.rs
Add a benchmark using [`criterion`](https://github.com/bheisler/criterion.rs) to benchmark DB performance,
specifically when the DB has a large number of profiles/items/items_tags.
Benchmark is heavily based on `tests/store_key.rs`
Please feel free to be extremely pedantic (`-Wclippy::pedantic -Wclippy::nursery`)
Related to #195
=> Add DB benchmark

docs/storage.md
Add some documentation explaining Database Proxying, referencing [pgBouncer](https://www.pgbouncer.org/) and [AWS RDS Proxy](https://aws.amazon.com/rds/proxy/).
=> DB Connection Pooling and Proxying docs

wrappers/javascript/aries-askar-nodejs/package.json, wrappers/javascript/aries-askar-nodejs/src/NodeJSAriesAskar.ts, wrappers/javascript/aries-askar-react-native/package.json, wrappers/javascript/aries-askar-react-native/src/ReactNativeAriesAskar.ts, wrappers/javascript/aries-askar-shared/package.json, wrappers/javascript/lerna.json
Some additional updates after #209.
It addresses two things:
- also handle error code mismatch in the promise callback
- update the RN implementation to handle the errors in the same way as we updated to in the node js wrapper. @berendsliedrecht you mentioned it was already implemented correctly in RN, were you talking about the unnessary error calling? Because the code matching logic was not present in the RN wrapper.
I've changed the mismatch behaviour handling to now throw an error with the original errorCode, and a custom message "Error has already been overwritten, unable to provide error message". That way it won't break the calling implementation, as long as they use errorCodes to  handle errors. I've looked and it seems we're not using error message from Askar anymore to do error …
=> fix(js): promise handle error and rn updates

.github/workflows/build.yml
Publishes dev version under alplha tag on NPM so install always gets the latest stable version rather than latest published version in general
=> ci(js): publish dev as alpha tag

askar-crypto/src/encrypt/crypto_box.rs
=> Fix panic when unsealing a value too short for a crypto box

wrappers/javascript/aries-askar-nodejs/package.json, wrappers/javascript/yarn.lock
Updated `ffi-napi` dependency on JS wrapper in order to fix the incompatibility issue found with newer node.js versions. See https://github.com/nodejs/node/issues/52240#issuecomment-2040598178.
=> fix(js): update ffi-napi

wrappers/javascript/aries-askar-react-native/android/build.gradle
This PR updates the react-native wrapper to get the `minSdkVersion` from the project config or fallback to the current hardcoded version.
I'm not entirely sure if anything else is needed but with this change I could get an app running on React Native 0.74. This change would also be needed in othe repos (`@hyperledger/anoncreds-react-native` and `@hyperledger/indy-vdr-react-native` at least) but I'd like to get approval here before spamming the other repos 😄
=> chore: update minSdkVersion to get the project version or fallback to 21

askar-storage/src/backend/sqlite/mod.rs
In SQLite comparison of expiry date is done using query
```sql
(expiry IS NULL OR expiry > DATETIME('now'))
```
but SQLite considers text strings for date and time comparisons by character order, not by their actual date/time value., so the check is not working correctly and askar returns the items stored even after expired.
The fix is easy, `expiry` should be first converted to DATETIME, in above query something like:
```sql
(expiry IS NULL OR DATETIME(expiry) > DATETIME('now'))
```
Fixes issue #260
=> fix: Incorrect SQLite expire check

.github/dependabot.yml, wrappers/python/requirements.dev.txt, wrappers/python/requirements.txt, wrappers/python/setup.py
Currently setup.py just indicates one dependency: `cached_property`.
It makes sense if the dependencies were parsed from a requirements.txt file (less effort than migrating to pyproject.toml format). Allows for easier management if any extras need to be added, and also means we can add pip dependency management to the dependabot workflow (namely to catch if there's an update to `cached_property`.
A requirements.dev.txt file is also added to track dev / test dependencies. I would add indy as a test requirement, since it's used in `indy_test.py`, but I can't find out which `indy` packages it's referring to ... it doesn't work with `pip install indy` or `python3-indy`. So for now I've just specified `pytest` and `pytest-asyncio`
=> Add python requirements file and update dependabot workflow

Cargo.toml, askar-crypto/Cargo.toml, wrappers/javascript/packages/aries-askar-nodejs/package.json, wrappers/javascript/packages/aries-askar-react-native/package.json, wrappers/javascript/packages/aries-askar-shared/package.json, wrappers/python/aries_askar/version.py
- Update aries-askar version (patch)
- Update askar-crypto version (patch)
- Update python wrapper version (patch)
- Update js wrapper versions (patch)
=> chore: update library versions

.github/workflows/build.yml
This should work for the python publish. 
Currently on my forked branch I get:
> ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
>          Invalid API Token: OIDC scoped token is not valid for project          
>          'aries-askar', project-scoped token is not valid for project:          
>          'aries-askar'        
but this is because the github action on my fork isn't in the repo matching aries-askar. It's a lot of work to rename everything to test with a personal pypi project, so I haven't done that.
I'm trying to figure out if can share this `environment` config amongst all the matrixes but I can't find much.
=> Update python publish workflow

wrappers/python/aries_askar/bindings/lib.py, wrappers/python/aries_askar/store.py, wrappers/python/requirements.txt
An error could be triggered when the library is loaded from multiple threads simultaneously (for example if a thread pool is used). This update adds a lock around the library initialization.
The `cached_property` dependency is also removed.
=> Fix race condition during Python library loading

Cargo.lock, Cargo.toml, askar-crypto/Cargo.toml, askar-crypto/src/alg/k256.rs, askar-crypto/src/alg/p256.rs, askar-crypto/src/alg/p384.rs, askar-crypto/src/buffer/array.rs, askar-crypto/src/buffer/secret.rs, askar-crypto/src/jwk/encode.rs, askar-storage/Cargo.toml, askar-storage/src/backend/db_utils.rs, askar-storage/src/backend/mod.rs, askar-storage/src/options.rs, askar-storage/src/protect/pass_key.rs, src/ffi/tags.rs, src/kms/enc.rs, wrappers/python/aries_askar/version.py
This fix affects the loading of k256, p256, and p384 secret keys. If a key of the wrong length was passed then a panic would occur rather than returning an error.
Also fixes a few clippy warnings and updates the package versions for a new release.
=> Fix panic when loading secret keys of invalid length

wrappers/python/aries_askar/bindings/handle.py, wrappers/python/aries_askar/bindings/lib.py, wrappers/python/aries_askar/store.py, wrappers/python/setup.cfg, wrappers/python/tests/test_store.py
From the Python library documentation it appears that the native `lru_cache` decorator could result in caching of Entry instances longer than necessary. This PR switches to a custom cache implementation at the EntryList level which should avoid any undesired behaviour.
@ff137
=> Python wrapper entry cache adjustment

askar-crypto/src/alg/k256.rs, askar-crypto/src/alg/p256.rs, askar-crypto/src/alg/p384.rs, askar-crypto/src/sign.rs, src/ffi/store.rs, src/store.rs, wrappers/python/tests/test_keys.py
This adds support for three new (non-JWA) signing algorithms accepting pre-hashed input. The input may be larger or smaller than the field size, allowing mixing of (for example) a SHA-384 hash with a P-256 signing key.
Fixes #371
=> Add support for prehashed signatures on EC curves

Cargo.lock, askar-storage/src/backend/db_utils.rs, askar-storage/src/backend/postgres/test_db.rs, askar-storage/src/backend/sqlite/mod.rs
Provide additional argument to `Transactionanager::begin` function to fix compilation errors
Closes #383
=> Update sqlx to 0.8.5 

Cargo.lock, askar-crypto/README.md, askar-crypto/benches/enc.rs, askar-crypto/benches/kdf.rs, askar-crypto/src/alg/any.rs, askar-crypto/src/alg/bls.rs, askar-crypto/src/alg/mod.rs, src/kms/local_key.rs, wrappers/python/aries_askar/types.py, wrappers/python/tests/test_keys.py
This updates the JWK encoding for BLS12-381 keys to match `draft-ietf-cose-bls-key-representations-06`.
The combined `G1G2` key type is removed as it wouldn't make sense in the new representation. Instead, `G1` and `G2` keypairs can be converted directly, as long as the private key is present.
=> Update BLS key JWK encoding

wrappers/python/aries_askar/bindings/__init__.py, wrappers/python/aries_askar/key.py
Small QOL improvement to correct type hints on the python wrapper. Parameters were marked as `str` but had a default value of `None` so their "true type" is `Optional[str]`. Propagated this expectation down the stack to bindings that are already handling potential None values.
=> feat: correct type hints on Key
